"""
State definitions and Pydantic schemas for SentinelPR.
"""

from enum import Enum
from typing import Annotated, Any, Dict, List, Optional
import operator
from pydantic import BaseModel, Field
from typing_extensions import TypedDict


class TrustZone(str, Enum):
    """Trust boundary classification for changed symbols."""
    PERIMETER = "PERIMETER"          # Public APIs, controllers, CLI, raw inputs
    INTERNAL_CORE = "INTERNAL_CORE"  # Domain models, internal services, typed helpers
    INTER_MODULE = "INTER_MODULE"    # Inter-subsystem boundary contracts


class Severity(str, Enum):
    """Severity levels for findings."""
    CRITICAL = "CRITICAL"      # RCE, severe data loss, auth bypass
    HIGH = "HIGH"              # Direct logic bug, high-risk race condition
    MEDIUM = "MEDIUM"          # Unhandled edge case, unoptimized leak
    LOW = "LOW"                # Code cleanliness, minor inefficiency
    SUGGESTION = "SUGGESTION"  # Constructive simplification / anti-bloat refactor


class FindingCategory(str, Enum):
    """Classification category of finding."""
    LOGIC = "LOGIC"
    SECURITY = "SECURITY"
    ANTI_BLOAT = "ANTI_BLOAT"
    RISK = "RISK"


class RiskLevel(str, Enum):
    """Risk tiers for PR blast radius and complexity."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskAssessment(BaseModel):
    """Assessment of overall pull request risk, blast radius, and test coverage."""
    risk_level: RiskLevel = RiskLevel.LOW
    cyclomatic_complexity: int = 0
    total_churn_lines: int = 0
    perimeter_symbols_count: int = 0
    has_test_coverage: bool = True
    summary: str = ""


class ProofStatus(str, Enum):
    """Dynamic test verification status."""
    UNTESTED = "UNTESTED"
    REPRODUCED_DYNAMICALLY = "REPRODUCED_DYNAMICALLY"
    NOT_REPRODUCED = "NOT_REPRODUCED"
    STATIC_VERIFIED = "STATIC_VERIFIED"
    ENV_SETUP_ERROR = "ENV_SETUP_ERROR"


class CriticDecision(str, Enum):
    """Verdict from the Adversarial Critic Gate."""
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    DOWNGRADE = "DOWNGRADE"


class DiffHunk(BaseModel):
    """Structured representation of a git diff hunk."""
    file_path: str
    old_start: int
    old_lines: int
    new_start: int
    new_lines: int
    content: str


class ASTSymbolScope(BaseModel):
    """An AST-derived symbol scope intersected with changed lines."""
    symbol_name: str
    symbol_type: str  # function, method, class, module
    file_path: str
    start_line: int
    end_line: int
    code_snippet: str
    trust_zone: TrustZone = TrustZone.INTERNAL_CORE
    imports: List[str] = Field(default_factory=list)


class Finding(BaseModel):
    """A code review finding generated by an agent."""
    id: str
    category: FindingCategory
    severity: Severity
    file_path: str
    start_line: int
    end_line: int
    title: str
    explanation: str
    suggested_fix: Optional[str] = None
    trust_zone: TrustZone = TrustZone.INTERNAL_CORE
    reproduction_script: Optional[str] = None
    proof_status: ProofStatus = ProofStatus.UNTESTED
    critic_decision: CriticDecision = CriticDecision.ACCEPT
    critic_reasoning: Optional[str] = None


class ConsolidatedReport(BaseModel):
    """Final output payload ready for GitHub and SARIF consumption."""
    summary_markdown: str
    inline_comments: List[Dict[str, Any]] = Field(default_factory=list)
    out_of_hunk_notes: List[Dict[str, Any]] = Field(default_factory=list)
    sarif_json: Dict[str, Any] = Field(default_factory=dict)
    total_findings_count: int = 0
    accepted_findings_count: int = 0
    rejected_findings_count: int = 0
    risk_assessment: Optional[RiskAssessment] = None


class PRReviewState(TypedDict):
    """
    Shared graph state for LangGraph execution.
    Uses Annotated[list, operator.add] to enable safe concurrent fan-out worker updates.
    """
    diff: str
    base_files: Dict[str, str]
    head_files: Dict[str, str]
    changed_files: List[str]
    hunks: List[DiffHunk]
    symbols: List[ASTSymbolScope]
    candidate_findings: Annotated[List[Finding], operator.add]
    repro_tests: Dict[str, str]  # finding_id -> test_code
    verified_findings: List[Finding]
    risk_assessment: Optional[RiskAssessment]
    consolidated_report: Optional[ConsolidatedReport]
