"""
State definitions and Pydantic schemas for SentinelPR.
"""

from enum import Enum
from typing import Annotated, Any, Dict, List, Literal, Optional
import operator
from pydantic import BaseModel, Field
from typing_extensions import TypedDict


class TrustZone(str, Enum):
    """Trust boundary classification for changed symbols."""
    PERIMETER = "PERIMETER"          # Public APIs, controllers, CLI, raw inputs
    INTERNAL_CORE = "INTERNAL_CORE"  # Domain models, internal services, typed helpers
    INTER_MODULE = "INTER_MODULE"    # Inter-subsystem boundary contracts


class Severity(str, Enum):
    """Severity levels for findings."""
    CRITICAL = "CRITICAL"      # RCE, severe data loss, auth bypass
    HIGH = "HIGH"              # Direct logic bug, high-risk race condition
    MEDIUM = "MEDIUM"          # Unhandled edge case, unoptimized leak
    LOW = "LOW"                # Code cleanliness, minor inefficiency
    SUGGESTION = "SUGGESTION"  # Constructive simplification / anti-bloat refactor


class FindingCategory(str, Enum):
    """Classification category of finding."""
    LOGIC = "LOGIC"
    SECURITY = "SECURITY"
    ANTI_BLOAT = "ANTI_BLOAT"
    RISK = "RISK"


class RiskLevel(str, Enum):
    """Risk tiers for PR blast radius and complexity."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskAssessment(BaseModel):
    """Assessment of overall pull request risk, blast radius, and test coverage."""
    risk_level: RiskLevel = RiskLevel.LOW
    cyclomatic_complexity: int = 0
    total_churn_lines: int = 0
    perimeter_symbols_count: int = 0
    has_test_coverage: bool = True
    summary: str = ""


class ProofStatus(str, Enum):
    """Dynamic test verification status."""
    UNTESTED = "UNTESTED"
    REPRODUCED_DYNAMICALLY = "REPRODUCED_DYNAMICALLY"
    NOT_REPRODUCED = "NOT_REPRODUCED"
    STATIC_VERIFIED = "STATIC_VERIFIED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    TIMEOUT = "TIMEOUT"
    SANDBOX_UNAVAILABLE = "SANDBOX_UNAVAILABLE"
    ENV_SETUP_ERROR = "ENV_SETUP_ERROR"  # Maintained for backward compatibility


class EvidenceSource(str, Enum):
    """Source of verification evidence for a finding."""
    STATIC_AST = "STATIC_AST"
    STATIC_PATTERN = "STATIC_PATTERN"
    DYNAMIC_SANDBOX = "DYNAMIC_SANDBOX"


class ReviewOutcome(str, Enum):
    """Final operational conclusion of the review process."""
    CLEAN = "CLEAN"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    INCOMPLETE_REVIEW = "INCOMPLETE_REVIEW"
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"


class ExactCodeReplacement(BaseModel):
    """Structured code replacement target with validated line boundaries."""
    file_path: str
    revision: str = "HEAD"
    start_line: int
    end_line: int
    replacement_text: str


class RiskIndicator(BaseModel):
    """Advisory risk metric (non-blocking)."""
    name: str
    severity: Severity = Severity.LOW
    metric_value: str
    description: str


class CriticDecision(str, Enum):
    """Verdict from the Adversarial Critic Gate."""
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    DOWNGRADE = "DOWNGRADE"


class DiffHunk(BaseModel):
    """Structured representation of a git diff hunk."""
    file_path: str
    old_start: int
    old_lines: int
    new_start: int
    new_lines: int
    content: str


class ASTSymbolScope(BaseModel):
    """An AST-derived symbol scope intersected with changed lines."""
    symbol_name: str
    symbol_type: str  # function, method, class, module
    file_path: str
    start_line: int
    end_line: int
    code_snippet: str
    trust_zone: TrustZone = TrustZone.INTERNAL_CORE
    imports: List[str] = Field(default_factory=list)


class Finding(BaseModel):
    """A code review finding generated by an agent."""
    id: str
    category: FindingCategory
    severity: Severity
    file_path: str
    start_line: int
    end_line: int
    title: str
    explanation: str
    suggested_fix: Optional[str] = None
    exact_replacement: Optional[ExactCodeReplacement] = None
    remediation_guidance: Optional[str] = None
    trust_zone: TrustZone = TrustZone.INTERNAL_CORE
    evidence_source: EvidenceSource = EvidenceSource.STATIC_AST
    reproduction_script: Optional[str] = None
    proof_status: ProofStatus = ProofStatus.UNTESTED
    proof_execution_log: Optional[str] = None
    critic_decision: CriticDecision = CriticDecision.ACCEPT
    critic_reasoning: Optional[str] = None


class RepositoryInventory(BaseModel):
    """Coverage of a local working-directory snapshot; target code is never executed."""
    root: str
    files: List[str] = Field(default_factory=list)
    analyzed_files: List[str] = Field(default_factory=list)
    context_files: List[str] = Field(default_factory=list)
    excluded_files: Dict[str, str] = Field(default_factory=dict)
    uninspected_files: Dict[str, str] = Field(default_factory=dict)


class ProjectAdvice(BaseModel):
    """Advisory engineering/delivery feedback, separate from code findings."""
    title: str = Field(min_length=1, max_length=200)
    priority: Literal["high", "medium", "low"]
    rationale: str = Field(min_length=1, max_length=2000)
    recommendation: str = Field(min_length=1, max_length=2000)
    evidence: List[str] = Field(default_factory=list, max_length=20)
    source: Literal["heuristic", "llm"] = "heuristic"


class ProjectAssessment(BaseModel):
    strengths: List[str] = Field(default_factory=list)
    advice: List[ProjectAdvice] = Field(default_factory=list)
    llm_summary: Optional[str] = None
    limitations: List[str] = Field(default_factory=list)
    llm_context_files: List[str] = Field(default_factory=list)


class ConsolidatedReport(BaseModel):
    """Final output payload ready for GitHub and SARIF consumption."""
    summary_markdown: str
    review_outcome: ReviewOutcome = ReviewOutcome.CLEAN
    inline_comments: List[Dict[str, Any]] = Field(default_factory=list)
    out_of_hunk_notes: List[Dict[str, Any]] = Field(default_factory=list)
    sarif_json: Dict[str, Any] = Field(default_factory=dict)
    total_findings_count: int = 0
    accepted_findings_count: int = 0
    rejected_findings_count: int = 0
    risk_assessment: Optional[RiskAssessment] = None
    risk_indicators: List[RiskIndicator] = Field(default_factory=list)
    uninspected_files: List[str] = Field(default_factory=list)
    repository_inventory: Optional[RepositoryInventory] = None
    project_assessment: Optional[ProjectAssessment] = None


class PRReviewState(TypedDict, total=False):
    """
    Shared graph state for LangGraph execution.
    Uses Annotated[list, operator.add] to enable safe concurrent fan-out worker updates.
    """
    diff: str
    base_files: Dict[str, str]
    head_files: Dict[str, str]
    changed_files: List[str]
    hunks: List[DiffHunk]
    symbols: List[ASTSymbolScope]
    candidate_findings: Annotated[List[Finding], operator.add]
    repro_tests: Dict[str, str]  # finding_id -> test_code
    verified_findings: List[Finding]
    risk_assessment: Optional[RiskAssessment]
    risk_indicators: Annotated[List[RiskIndicator], operator.add]
    uninspected_files: Annotated[List[str], operator.add]
    review_outcome: Optional[ReviewOutcome]
    consolidated_report: Optional[ConsolidatedReport]

    repository_inventory: RepositoryInventory
    project_assessment: ProjectAssessment
